version : "3.8"

services:
   backend:
       build: ./backend
       container_name: connect-backend
       ports:
        - "8080:8080"
       env_file:
        - ./backend/.env 
       networks:
        - ce-network
  
networks :
  ce-network :
       